Feature/header
AndrewKustov1998/mimino pull request #12
Opened 2022-12-03 19:50 UTC by AntoninaKobzar

Привіт, перевірте  header, будьласка.

2022-12-03 22:55 UTC, eNgine9r commented on src/sass/layout/_header.scss
> +    letter-spacing: 0.3em;
(letter-spacing: 0.3em;) за замовчуванням, можна видалити

2022-12-03 22:55 UTC, eNgine9r commented on src/sass/layout/_header.scss
> +    line-height: 0.92;
39/36=1.08
потрібно виправити
line-height: 1.08;

2022-12-03 22:55 UTC, eNgine9r commented on src/sass/layout/_header.scss
> +    line-height: 1.22;
20/16=1.25
потрібно виправити
line-height: 1.25;

2022-12-04 10:18 UTC, eNgine9r approved these changes

2022-12-04 18:49 UTC, AndrewKustov1998 requested changes
Виправити зміни.

2022-12-04 18:49 UTC, AndrewKustov1998 commented on src/partials/header.html
> +      <a class="site-nav__logo" href="/src/index.html">MIMIHO</a>
у нас є блок _company-title
використай цей клас для стилізації логотипу

2022-12-04 18:49 UTC, AndrewKustov1998 commented on src/sass/layout/_header.scss
> +.site-nav__logo {
є окремий блок _company-title
використай його, а цей код видали

2022-12-04 18:49 UTC, AndrewKustov1998 commented on src/sass/layout/_header.scss
> +    font-family: 'Montserrat';
можна видалити
цей шрифт наслідується

2022-12-04 18:49 UTC, AndrewKustov1998 commented on src/sass/layout/_header.scss
> +    font-style: normal;
можна видалити
цей параметр використовується за замовчуванням

2022-12-04 18:49 UTC, AndrewKustov1998 commented on src/sass/layout/_header.scss
> +    text-decoration: none;
у нас є базовий клас link
додай цей клас на посилання і застосується  text-decoration: none;
а тут видали

2022-12-04 18:49 UTC, AndrewKustov1998 commented on src/sass/layout/_header.scss
> +    display: flex;
тут додай gap 6px
у тебе немає відступу між елементами
![image](https://user-images.githubusercontent.com/49692033/205508850-e581c21d-b00e-4e74-b386-b7485cde1b68.png)
![image](https://user-images.githubusercontent.com/49692033/205508855-0a03bd9a-a925-4b63-b808-da163a6d8d66.png)

2022-12-04 18:49 UTC, AndrewKustov1998 commented on src/sass/layout/_header.scss
> +.page-header__container {
властивості для контейнеру
    width: 100%;
    max-width: 414px;
    justify-content: space-between;
    align-items: center;
    padding: 17px 15px;
    display: flex;

2022-12-04 18:49 UTC, AndrewKustov1998 commented on src/sass/layout/_header.scss
> +.site-nav {
це прибери
працює некоректно
![image](https://user-images.githubusercontent.com/49692033/205509025-13cf1328-3fb3-4947-827e-86c83ada63a8.png)

2022-12-04 18:49 UTC, AndrewKustov1998 commented on src/sass/layout/_header.scss
> +        margin-left: 8px;
прибери margin-left: 8px;
додай краще gap

2022-12-04 18:49 UTC, AndrewKustov1998 commented on src/sass/layout/_header.scss
> +.site-nav__phone {
для свг телефону немає лівого відстуту
![image](https://user-images.githubusercontent.com/49692033/205509299-92dd5680-d143-494b-859f-d9c1f78bed26.png)
![image](https://user-images.githubusercontent.com/49692033/205509311-3538f2fa-53dd-4506-bd21-d5d1cac6d6d9.png)

2022-12-04 23:38 UTC, AntoninaKobzar commented on src/sass/layout/_header.scss
> +.page-header__container {
padding17 зайві

2022-12-04 23:38 UTC, AntoninaKobzar commented on src/sass/layout/_header.scss
> +.site-nav {
лишаємо

2022-12-05 00:08 UTC, AntoninaKobzar commented on src/sass/layout/_header.scss
> +        margin-left: 8px;
лишила,бо ламається структура

2022-12-05 06:10 UTC, AndrewKustov1998 requested changes
Виправ будь ласка ці 2 моменти 
В цілому все добре!

2022-12-05 06:10 UTC, AndrewKustov1998 commented on src/sass/layout/_header.scss
> +
огорни site-nav та company-title у ще один div
дай якусь назву, і цьому класу дай властивіть justify-content: space-between;   display: flex;
прибери margin-right для лого

подивись відео, чому потрібно це зробити 
https://www.loom.com/share/ec359d1048aa4746b1e1e4961d41c0dc

2022-12-05 12:55 UTC, AndrewKustov1998 commented
чекаю на зміни

2022-12-05 17:44 UTC, AntoninaKobzar commented on src/sass/layout/_header.scss
> +
Зміни внесено,працює,але з max-width не вийшло

2022-12-06 06:48 UTC, AndrewKustov1998 approved these changes
добре

2022-12-06 06:48 UTC, merged