Feature/amenities
AndrewKustov1998/mimino pull request #13
Opened 2022-12-04 01:28 UTC by ValentynaSira1

Робота над секцією amenities завершена.

2022-12-04 16:52 UTC, AntoninaKobzar commented on src/partials/room-page/amenities.html
> -                Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.
Цей абзац краще оформити тегом <p>, а не частиною списку

2022-12-04 16:55 UTC, AntoninaKobzar commented on src/partials/room-page/amenities.html
> +                    Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.
описові частини, мабуть повинні бути обернені у тег <p>

2022-12-04 16:56 UTC, AntoninaKobzar commented on src/partials/room-page/amenities.html
> +                    Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.
Привіт! Описові частини, мабуть повинні бути обернені у тег <p>

2022-12-04 17:14 UTC, AntoninaKobzar commented on src/partials/room-page/amenities.html
> +                    Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.
Привіт! Описові частини, мабуть,
повинні бути обернені у тег <p>

2022-12-04 17:31 UTC, AntoninaKobzar commented on src/partials/room-page/amenities.html
> +            <ul class="list amenities__list">
Згідно завдання список `<ul>`amenities__list складається з 5 `<li>`,підзаголовки(загальні,ванна кімната,спальня і т.д.),і `<p>`(у 1,2 і 4 лішках по 2 `<p>`.

2022-12-04 17:55 UTC, AntoninaKobzar commented on src/sass/components/room-page/_amenities.scss
> +        padding: 32px 0 16px 0;
для таблет і десктоп 48 верхній падинг

2022-12-04 22:55 UTC, AntoninaKobzar approved these changes

2022-12-05 06:39 UTC, AndrewKustov1998 requested changes
Додай зміни і я запушу в мейн
Дкую за роботу!

2022-12-05 06:39 UTC, AndrewKustov1998 commented on src/sass/components/room-page/_amenities.scss
> +        padding-bottom: 16px;
відступи робимо маржинами, а не падінгами

2022-12-05 06:39 UTC, AndrewKustov1998 commented on src/sass/components/room-page/_amenities.scss
> +        padding-bottom: 16px;
відступи робимо маржинами, а не падінгами

2022-12-05 06:48 UTC, ValentynaSira1 commented on src/sass/components/room-page/_amenities.scss
> +        padding-bottom: 16px;
виконано

2022-12-05 06:49 UTC, ValentynaSira1 commented on src/sass/components/room-page/_amenities.scss
> +        padding-bottom: 16px;
виконано

2022-12-05 06:53 UTC, AndrewKustov1998 approved these changes
все добре

2022-12-05 06:53 UTC, merged