Feature/home page section
AndrewKustov1998/mimino pull request #14
Opened 2022-12-04 01:29 UTC by Bytenkonatasha

Робота з секцією about-our-hotel завершена

2022-12-04 12:59 UTC, n-ruzhik requested changes

2022-12-04 12:59 UTC, n-ruzhik commented on src/sass/components/home-page/_about-our-hotel.scss
> +        margin-left: 143px;
цей елемент я б радила позиціонувати не через лівий марджин, а додати параграфу тексту width згідно макету, + додати align-items: flex-end для діва, в якому цей параграф знаходиться.  Відповідно пофіксити позиціонування div "about-hotel__box" і елементів всередині нього для таблетки+десктопа.

2022-12-04 12:59 UTC, n-ruzhik commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__title {
вирівняти елемент mimino по правому краю контейнера у всіх версіях адаптивки.

2022-12-04 12:59 UTC, n-ruzhik commented on src/sass/components/home-page/_about-our-hotel.scss
> +        margin-right: 21px;
забрати правий марджин. У діва, який огортає фото і абзац є властивість space-beetwen, що розмістить елементи всередині нього по краях. Цього буде достатньо

2022-12-04 12:59 UTC, n-ruzhik commented on src/partials/home-page/about-our-hotel.html
> +            </picture>
додати в розмітку свг-іконки зі стрілочками для підключення слайдера.

2022-12-04 12:59 UTC, n-ruzhik commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__wrapper {
Зовнішній відступ від елемента додається марджином, а не паддінгом. Також він має бути лише у мобайл-версії. У таблетці та десктопній версії його треба забрати.

2022-12-04 12:59 UTC, n-ruzhik commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__slider {
Позиціонування картинок слайдера у таблетці не відповідає макету. (зображення в макеті розташовані трохи вище, ніби "заїжджають" на дів, що над ними).

2022-12-04 12:59 UTC, n-ruzhik commented on src/partials/home-page/about-our-hotel.html
> +            <h4 class="company-title about-hotel__subtitle">MIMIHO</h4>
в коді краще не використовувати капслок, а прописувати текст в нижньому регісті (за порадою Репети). Щоб зробити всі літери великими на живій сторінці, в стилях краще прописати до класу властивість text-transform: uppercase;

2022-12-04 12:59 UTC, n-ruzhik commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__title {
в таблетці + десктопі нижній марджин 4px.

2022-12-04 12:59 UTC, n-ruzhik commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__subtitle {
в таблетці + десктопі нижній марджин 24px.

2022-12-04 18:37 UTC, Bytenkonatasha commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__slider {
Доброго вечора. Можна уточнити щодо розташування на таблетці фото для слайдеру, вони в мене заїзджають на верхній дів, не можу зрозуміти що не так.

2022-12-04 23:47 UTC, Bytenkonatasha commented on src/sass/components/home-page/_about-our-hotel.scss
> +.about-hotel {
Виправлено

2022-12-04 23:47 UTC, Bytenkonatasha commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__box {
Виправлено

2022-12-04 23:47 UTC, Bytenkonatasha commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__subtitle {
Виправлено

2022-12-04 23:47 UTC, Bytenkonatasha commented on src/sass/components/home-page/_about-our-hotel.scss
> +        margin-left: 143px;
Виправлено

2022-12-04 23:48 UTC, Bytenkonatasha commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__title {
Виправлено

2022-12-04 23:48 UTC, Bytenkonatasha commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__wrapper {
Виправлено

2022-12-04 23:48 UTC, Bytenkonatasha commented on src/partials/home-page/about-our-hotel.html
> +            <h4 class="company-title about-hotel__subtitle">MIMIHO</h4>
Виправлено

2022-12-04 23:48 UTC, Bytenkonatasha commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__title {
Виправлено

2022-12-04 23:48 UTC, Bytenkonatasha commented on src/sass/components/home-page/_about-our-hotel.scss
> +    &__subtitle {
Виправлено

2022-12-05 07:25 UTC, n-ruzhik requested changes

2022-12-05 07:25 UTC, n-ruzhik commented on src/partials/home-page/about-our-hotel.html
> +        </div>
додайте, будь ласка, іконки з свг-спрайту зі стрілочками для слайдера.
І гляньте до десктопної версії, під картинками слайдера з'явився великий відступ до низу секції (на макеті він значно менший)

2022-12-05 08:51 UTC, Bytenkonatasha commented on src/partials/home-page/about-our-hotel.html
> +        </div>
Додано та все виправлено

2022-12-05 13:22 UTC, AndrewKustov1998 commented
Коментар від Наталії
Залишилося:
Треба лише вірно в  html написати міміно, літера невірна, але в мене немає світла та інтернету. Як тільки дадуть хоч інтернет спробую зробити.

2022-12-05 20:34 UTC, AndrewKustov1998 commented
добре
слайдер треба буде підключити

2022-12-05 20:34 UTC, merged