Feature/hotel page
AndrewKustov1998/mimino pull request #15
Opened 2022-12-04 07:43 UTC by Cymbalenk

Add sections hotel page 2,4

2022-12-04 15:05 UTC, Bytenkonatasha commented on src/partials/hotel-page/luxe-for-two-adults.html
> +    <div class="set">
рекомендую додати верхній та нижній падінг на всю секцію (наприклад на мобільну версію 32рх). На зараз нижнього падінгу ви не поставили.

2022-12-04 15:11 UTC, Bytenkonatasha commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <h2 class="section-room-luks__label">MIMIHO</h2>
Змінини колір тексту на мобільці та таблетці на #494848

2022-12-04 16:06 UTC, Bytenkonatasha requested changes

2022-12-04 19:41 UTC, Cymbalenk commented on src/partials/hotel-page/luxe-for-two-adults.html
> +      <ul class="list-grup">
Исправленно

2022-12-04 19:41 UTC, Cymbalenk commented on src/partials/hotel-page/luxe-for-two-adults.html
> +    <div class="set">
Исправленно

2022-12-04 19:42 UTC, Cymbalenk commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <p class="section-room-luks__text">Amet minim mollit non</p>
Исправленно

2022-12-04 19:43 UTC, Cymbalenk commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <h2 class="section-room-luks__label">MIMIHO</h2>
Исправленно

2022-12-04 20:01 UTC, Cymbalenk commented on src/partials/hotel-page/luxe-for-two-adults.html
> +
Исправленно

2022-12-04 20:23 UTC, Cymbalenk commented on src/partials/hotel-page/luxe-for-two-adults.html
> +      <li><button class="room-luks__button">Переглянути ціни</button></li>
Исправленно

2022-12-04 20:31 UTC, Cymbalenk commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <h3 class="section-room-luks__title">ДВОМІСНИЙ НОМЕР люкс</h3>
Исправленно

2022-12-05 00:21 UTC, Bytenkonatasha commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <p class="section-room-luks__text">Amet minim mollit non</p>
На мобілку має бути 8рх.

2022-12-05 07:10 UTC, Cymbalenk commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <p class="section-room-periud">Amet minim mollit non deserunt ullamco est sit aliqua dolor do
Исправленно

2022-12-05 07:13 UTC, Cymbalenk commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <p class="section-room-luks__text">Amet minim mollit non</p>
Исправленно

2022-12-05 16:53 UTC, Bytenkonatasha commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <p class="section-room-luks__text">Amet minim mollit non</p>
Додати відступ між Amet minim mollit non і MIMIHO

2022-12-05 17:50 UTC, Bytenkonatasha requested changes

2022-12-05 17:50 UTC, Bytenkonatasha commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <h3 class="section-room-luks__title">ДВОМІСНИЙ НОМЕР люкс</h3>
На мобільці текст має бути font-weight: 700 і в html прописати текст без caps lock і через стилі text-transform: uppercase. В десктопі font-size: 36px;

2022-12-05 17:50 UTC, Bytenkonatasha commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <p class="section-room-periud">Amet minim mollit non deserunt ullamco est sit aliqua dolor do
Не змінили font-weight на 600

2022-12-05 17:50 UTC, Bytenkonatasha commented on src/partials/hotel-page/luxe-for-two-adults.html
> +  <p class="section-room-luks__text">Amet minim mollit non</p>
На таблетку розмір тексту font-size: 32px

2022-12-05 17:50 UTC, Bytenkonatasha commented on src/partials/hotel-page/luxe-for-two-adults.html
> +      <div>
Додати лінії які йдуть через всю сторінку

2022-12-06 11:01 UTC, closed without merging