Feature/heroes
AndrewKustov1998/mimino pull request #16
Opened 2022-12-04 07:46 UTC by Marik-Dima

will try to finish at Sunday 

issues with font for Logo -  class logo don't applying

2022-12-04 15:29 UTC, mary-chery requested changes

2022-12-04 15:29 UTC, mary-chery commented on src/partials/home-page/home-hero.html
> +
для того чтоб изображение было адаптивным для моб таб и десктоп- нужно вешать его не на секцию, а обернуть эту секцию в див и цеплять изображения на него. секция ограничена контейнером, поэтому изображения не тянутся

2022-12-04 15:29 UTC, mary-chery commented on src/partials/home-page/home-hero.html
> +
в таб и дескто-кнопки и адрес должны быть в один ряд, для этого я рекомендую через медиа правило скрыть див с адресом , оставить видным только для моб версии, а затем скопировать html код дива адреса и вставить ее перед кнопками, обернуть в еще один див адресс+кнопки и спозиционировать через дисплей флекс, и space-betwen. затем через медиа правило сделать его видным только для таблет и десктоп

2022-12-04 15:29 UTC, mary-chery commented on src/partials/home-page/home-hero.html
> +        <h3 class="company-slogan company-slogan--hero">Смак життя 24/7</h3>
через медиа правило необходимо задать другие размеры шрифта для таб и десктоп
h2-font-size: 20px;
line-height: 24px;
h3-font-size: 36px;
line-height: 41px;

2022-12-04 15:30 UTC, mary-chery commented
https://github.com/AndrewKustov1998/mimino/pull/18/files

код героя отеля, для примера

2022-12-05 22:32 UTC, Marik-Dima commented on src/partials/home-page/home-hero.html
> +
выправлена

2022-12-05 22:32 UTC, Marik-Dima commented on src/partials/home-page/home-hero.html
> +        <h3 class="company-slogan company-slogan--hero">Смак життя 24/7</h3>
+

2022-12-05 22:33 UTC, merged