hotel-hero
AndrewKustov1998/mimino pull request #18
Opened 2022-12-04 10:48 UTC by mary-chery

2022-12-04 18:24 UTC, Cymbalenk commented on src/partials/hotel-page/hotel-hero.html
> +    <h1 class="hotel-hero__maintitle">MIMIHO</h1>
В версии таблетки и десктоп добавить font-size 128px font-height 138px

2022-12-04 18:32 UTC, Cymbalenk commented on src/partials/hotel-page/hotel-hero.html
> +            <div class="hotel-hero__adress hotel-hero__adress--tab">
В мобильной версии выходит за границу контейнера

2022-12-04 18:33 UTC, Cymbalenk commented on src/partials/hotel-page/hotel-hero.html
> +<div class="bcg-hero">
В десктопной версии слева и справа не все изображение отображается

2022-12-04 18:38 UTC, Cymbalenk commented on src/partials/hotel-page/hotel-hero.html
> +        <div class="hotel-hero__position-tab">
В мобильной версии не хватает вертикального отступа,в версии таблетки и десктоп нужно выровнять по вертикали

2022-12-04 18:42 UTC, Cymbalenk commented on src/partials/hotel-page/hotel-hero.html
> +        <li class="list hotel-hero__list">
В мобильной версии лишний левый марджин у первой иконки соц сетей,а в версии таблетки лишний нижний марджин у соц сетей

2022-12-04 18:44 UTC, Cymbalenk commented on src/partials/hotel-page/hotel-hero.html
> +    <ul class="hotel-hero__social-link">
В десктопной версии группа из соц-сетей должна быть по макету в верхнем правом углу

2022-12-04 18:47 UTC, mary-chery commented on src/partials/hotel-page/hotel-hero.html
> +    <ul class="hotel-hero__social-link">
точно,недосмотрела, в десктопе это часть хедера

2022-12-04 18:57 UTC, Cymbalenk requested changes
Я просмотрел ваш код секции,если что-то будет не ясно из того что я написам в коментах,буду рад подсказать.

2022-12-05 08:05 UTC, Cymbalenk commented on src/partials/hotel-page/hotel-hero.html
> +        <div class="hotel-hero__position-tab">
Hotel-hero__position-tab нужно слегка выровнять по нижнему краю если я правильно вижу на макете)

2022-12-05 08:34 UTC, Cymbalenk commented on src/partials/hotel-page/hotel-hero.html
> +                <a class="hotel-hero__adresslink" href="https://goo.gl/maps/A1TdqW8fbpUCnmj5A" target="_blank"
Здесь нужно с свг придумать что-то ,она на макете больше,и текст не так расположен как в макете.

2022-12-05 08:38 UTC, Cymbalenk requested changes
Просмотрел ваш код, извините что так долго не было электричества

2022-12-05 09:40 UTC, mary-chery commented
all fix

2022-12-05 11:43 UTC, mary-chery commented on src/partials/hotel-page/hotel-hero.html
> +    <h1 class="hotel-hero__maintitle">MIMIHO</h1>
добавила

2022-12-05 11:44 UTC, mary-chery commented on src/partials/hotel-page/hotel-hero.html
> +        <li class="list hotel-hero__list">
fix

2022-12-05 11:44 UTC, mary-chery commented on src/partials/hotel-page/hotel-hero.html
> +        <div class="hotel-hero__position-tab">
fix

2022-12-05 11:44 UTC, mary-chery commented on src/partials/hotel-page/hotel-hero.html
> +            <div class="hotel-hero__adress hotel-hero__adress--tab">
fix

2022-12-05 12:10 UTC, AndrewKustov1998 requested changes
Чекаю на зміни

2022-12-05 12:10 UTC, AndrewKustov1998 commented on src/sass/components/hotel-page/_hotel-hero.scss
> +            padding-bottom: 15px;
ми робимо відступ маржином, а не падінгом

2022-12-05 12:10 UTC, AndrewKustov1998 commented on src/sass/components/hotel-page/_hotel-hero.scss
> +button {
у нас є блок з кнопками (_main-button.scss)
я бачу що у тебе не має цього блоку
тому онови перед цим свою локальну  гілку мейн та свою гілку
використай та налаштуй ті кнопки, а ці видали

2022-12-05 12:10 UTC, AndrewKustov1998 commented on src/sass/components/hotel-page/_hotel-hero.scss
> +            padding-bottom: 64px;
ми робимо відступ маржином, а не падінгом

2022-12-05 12:10 UTC, AndrewKustov1998 commented on src/sass/components/hotel-page/_hotel-hero.scss
> +.bcg-hero {
Блок з соц мережами зникає при ширині 1280 і більше
треба розібратися
https://www.loom.com/share/6e283808521f4970b9108014530fd793

2022-12-05 12:19 UTC, mary-chery commented on src/sass/components/hotel-page/_hotel-hero.scss
> +.bcg-hero {
потому что на десктопе он часть хедера

2022-12-05 12:34 UTC, mary-chery commented on src/sass/components/hotel-page/_hotel-hero.scss
> +            padding-bottom: 64px;
-

2022-12-05 12:34 UTC, mary-chery commented on src/sass/components/hotel-page/_hotel-hero.scss
> +            padding-bottom: 15px;
-

2022-12-05 12:35 UTC, mary-chery commented on src/sass/components/hotel-page/_hotel-hero.scss
> +    padding-bottom: 20px;
-

2022-12-05 12:35 UTC, mary-chery commented on src/partials/hotel-page/hotel-hero.html
>  <br />Розмітка секції "Герой" (секція 1)
fix

2022-12-05 12:35 UTC, mary-chery commented on src/partials/hotel-page/hotel-hero.html
> +    <h1 class="hotel-hero__maintitle">MIMIHO</h1>
fix

2022-12-05 18:51 UTC, mary-chery commented on src/sass/components/hotel-page/_hotel-hero.scss
> +button {
fix

2022-12-05 21:05 UTC, merged