Feature/contacts
AndrewKustov1998/mimino pull request #8
Opened 2022-12-03 15:17 UTC by n-ruzhik

The branch creates a Contact section for the Home Page.
Layout, styles, positioning and responsiveness are added according to the layout.

P.S: added 11px gap instead of 12px in class  .contacts-list__link--united.
If we do 12px, the phone numbers are wrapping (I assume it's due to the borders of the element in which they are placed).

2022-12-04 14:48 UTC, maryelisss requested changes

2022-12-04 14:48 UTC, maryelisss commented on src/partials/home-page/contacts.html
> +      <p class="company-title company-title--gray" lang="uk">mimino</p>
Замінити тег `<p>` на `<h>`
Замінити текст на "mimiho"

2022-12-04 14:48 UTC, maryelisss commented on src/partials/home-page/contacts.html
> +          <p class="contacts-list__title">Ресторан</p>
Замінити тег `<p>` на `<h>`

2022-12-04 14:48 UTC, maryelisss commented on src/partials/home-page/contacts.html
> +          <p class="contacts-list__title">Готель</p>
Замінити тег `<p>` на `<h>`

2022-12-04 14:48 UTC, maryelisss commented on src/partials/home-page/contacts.html
> +          <p class="contacts-list__title contacts-list__title--hidden">
Замінити тег `<p>` на `<h>`

2022-12-04 14:48 UTC, maryelisss commented on src/partials/home-page/contacts.html
> +          >
В рамочці з посиланням адреси завеликий паддінг справа, де він в файлі стилів не знайшла, скрін скинула в особисті повідомлення в слак

2022-12-04 14:48 UTC, maryelisss commented on src/sass/components/home-page/_contacts.scss
> +    box-shadow: 2px 2px 60px 2px rgba(0, 0, 0, 0.25);
тінь не співпадає з тінню в макеті, для таблета і десктопа має бути `box-shadow: 5px 5px 70px 17px`

2022-12-04 14:48 UTC, maryelisss commented on src/sass/components/home-page/_contacts.scss
> +    font-size: 14px;
Невірно заданий розмір шрифта. Має бути 
`font-weight: 400;
font-size: 16px;
line-height: 1,25;
letter-spacing: 0.01em;`

2022-12-04 21:38 UTC, AndrewKustov1998 commented on src/partials/home-page/contacts.html
> +          >
скріни можна кидати і тут

2022-12-04 21:46 UTC, AndrewKustov1998 approved these changes
бачу зміни
пушу в мейн

2022-12-04 21:57 UTC, maryelisss approved these changes

2022-12-04 21:58 UTC, merged

2022-12-05 14:11 UTC, n-ruzhik commented on src/partials/home-page/contacts.html
> +      <p class="company-title company-title--gray" lang="uk">mimino</p>
done

2022-12-05 14:12 UTC, n-ruzhik commented on src/partials/home-page/contacts.html
> +          <p class="contacts-list__title">Ресторан</p>
done

2022-12-05 14:12 UTC, n-ruzhik commented on src/partials/home-page/contacts.html
> +          <p class="contacts-list__title">Готель</p>
done

2022-12-05 14:12 UTC, n-ruzhik commented on src/partials/home-page/contacts.html
> +          >
done

2022-12-05 14:12 UTC, n-ruzhik commented on src/sass/components/home-page/_contacts.scss
> +    box-shadow: 2px 2px 60px 2px rgba(0, 0, 0, 0.25);
done

2022-12-05 14:12 UTC, n-ruzhik commented on src/sass/components/home-page/_contacts.scss
> +    font-size: 14px;
done