Feature/room for three adults
AndrewKustov1998/mimino pull request #9
Opened 2022-12-03 15:29 UTC by Boroda-Dmitro

добавляє розмітку та стилі трьохмісного номеру на сторінці готель.

2022-12-04 17:23 UTC, ValentynaSira1 requested changes

2022-12-04 17:23 UTC, ValentynaSira1 commented on src/partials/hotel-page/room-for-three-adults.html
> +        <h2 class="three-adults__title">Трьохмісний номер</h2>
На таблетці відстань від заголовку до параграфу 16 рх, а в десктопі 24рх.

2022-12-04 17:23 UTC, ValentynaSira1 commented on src/partials/hotel-page/room-for-three-adults.html
> +          <div class="slider__img"></div>
На таблетці відстань між картинками повинна бути 40 рх, а вниз до стрілок - 32рх, на десктопі між картинками - 40рх, і вниз до стрілок - 40 рх.

2022-12-04 17:23 UTC, ValentynaSira1 commented on src/partials/hotel-page/room-for-three-adults.html
> +        <p class="three-adults__text">
На десктопі жирність тексту 700

2022-12-04 19:57 UTC, Boroda-Dmitro commented on src/partials/hotel-page/room-for-three-adults.html
> +      <div class="three-adults__img"></div>
готово

2022-12-04 20:00 UTC, Boroda-Dmitro commented on src/partials/hotel-page/room-for-three-adults.html
> +          <div class="slider__img"></div>
готово

2022-12-04 20:00 UTC, Boroda-Dmitro commented on src/partials/hotel-page/room-for-three-adults.html
> +        <p class="three-adults__text">
готово

2022-12-04 22:59 UTC, ValentynaSira1 commented on src/partials/hotel-page/room-for-three-adults.html
> +        <p class="three-adults__text">
виправте помилку в слові

2022-12-04 23:07 UTC, ValentynaSira1 approved these changes

2022-12-05 07:07 UTC, AndrewKustov1998 approved these changes
все добре

2022-12-05 07:07 UTC, merged